default_language_version:
  python: python3.14
fail_fast: true
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: pretty-format-json
        args: [--autofix, --no-ensure-ascii]
      - id: check-added-large-files
        args: [--maxkb=1024]
      - id: check-merge-conflict
      - id: check-case-conflict
      - id: mixed-line-ending
      - id: debug-statements
      - id: detect-private-key
      - id: no-commit-to-branch
        args: [--branch, main]

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
      - id: add-trailing-comma

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.0
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.12.0
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: trivy-fs
        name: trivy-fs
        entry: trivy fs --scanners vuln --severity CRITICAL,HIGH --exit-code 1 .
        language: system
        pass_filenames: false
        require_serial: true
      - id: check-msg
        name: check-msg
        language: pygrep
        entry: '\A(?!\[SB\d{1,2}\]\s)'
        args: [--multiline]
        stages: [commit-msg]
      - id: mypy
        name: mypy
        entry: uv run mypy .
        language: system
        types: [python]
        pass_filenames: false
        require_serial: true
