"""Placeholder entry point generated by the project scaffold."""


def main() -> None:
    """Print a greeting."""
    print('Hello from keytom-simplebank-api-3!')


if __name__ == '__main__':
    main()
