[project]
name = "keytom-simplebank-api-3"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14.0"
dependencies = [
    "django>=6.0.7",
    "django-ninja>=1.6.2",
    "psycopg[binary]>=3.3.4",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.7.0",
]

[dependency-groups]
dev = [
    "django-stubs>=6.0.7",
    "mypy>=2.3.0",
    "pre-commit>=4.6.1",
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
    "ruff>=0.16.0",
    "testcontainers[postgres]>=4.15.0",
]

[tool.ruff.format]
quote-style = "single"

[tool.mypy]
plugins = ["mypy_django_plugin.main"]
python_version = "3.14"
exclude = ["migrations/"]

[tool.django-stubs]
django_settings_module = "simplebank.settings.environments.local"

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "simplebank.settings.environments.local"
python_files = ["test_*.py"]
